mykg/demo/urls.py
from django.conf.urls import url
from django.urls import path

from . import QA_view,entity_view,up_views,index_view,relation_view,annotation,over_view,ner_view,login_view
from .login_view import user
from .views import *
app_name = 'demo'
urlpatterns = [
    # path('',base),
    path('',over_view.over_view),
    path('login/',login_view.login, name="Login"),
    path('up/',annotation.local_a),
    path('shibie/',index_view.index),
    path('logout/',login_view.logout,name='Logout'),
    path('register/',login_view.register,name="register"),
    path('users/', user),
    path('overview/',over_view.over_view),
    path('QA/',QA_view.question_answering),
    path('annotating/',annotation.to_fileupload),
    path('local/',annotation.local,name='local'),
    path('relation/',entity_view.search_relation),
    path('test/',relation_view.relation),
    path('search_entity/',entity_view.entity),
    path('ER-post/',ner_view.ner_post),
]

mykg/mykg/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views import static

from demo.views import base
from mykg import settings
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo.urls')),
    # url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
    #     'document_root': settings.STATIC_ROOT,
    # }),
]

mykg/demo/models.py
from django.db import models

# Create your models here.
from django.db import models

mykg/rabc/models.py
from django.db import models


# Create your models here.
class Permission(models.Model):
    """
    权限表
    """
    url = models.CharField(max_length=64)
    title = models.CharField(max_length=10)

    class Meta:
        verbose_name = '权限表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色表
    """
    title = models.CharField(max_length=10)
    permission = models.ManyToManyField(Permission, null=True, blank=True)

    class Meta:
        verbose_name = '角色表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class User(models.Model):
    """
    用户表
    """
    name = models.CharField(max_length=32)
    pwd = models.CharField(max_length=32)
    email = models.EmailField(blank=True)
    role = models.ManyToManyField(Role, null=True, blank=True)

    class Meta:
        verbose_name = '用户表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

mykg/demo/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def base(request):
    return render(request,"base.html",None)

mykg/rabc/views.py
from django.shortcuts import render

# Create your views here.

mykg/templates/annotate.html
{% extends "base.html" %} {% block mainbody %}
    <style>
        .file,texts{
        position: relative;
        display: inline-block;
        background: #D0EEFF;
        border: 1px solid #99D3F5;
        border-radius: 4px;
        padding: 4px 12px;
        overflow: hidden;
        color: #1E88C7;
        text-decoration: none;
        text-indent: 0;
        line-height: 20px;
    }
    .file input {
        position: absolute;
        font-size: 100px;
        right: 0;
        top: 0;
        opacity: 0;
    }
    .file:hover {
        background: #AADFFD;
        border-color: #78C3F3;
        color: #004974;
        text-decoration: none;
    }
    </style>

    <div style="position: center;text-align:center;border: #00a0df 1px solid ;padding: 20px" id="it">
        <form action="{% url 'demo:local' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <table class="table table-condensed">
                <tr>
                       <td>
                 <div class="file">选择压缩包<input type="file" name="file"></div>
                   </td>
                </tr>
                <tr>
                       <td>
                   <div class="showFileName"></div>
                   </td>
                </tr>
                <tr>
{#                    <td rowspan=$rowspan style='vertical-align: middle;text-align: center;' ><input type="submit" style="background:#AADFFD " value="上传"></td>#}
                    			       <td><div class="btn-group" style="padding: 2%">
			            <button type="submit"  class="btn btn-primary" >上传</button>
			        </div></td>
                </tr>
            </table>

            <div class="fileerrorTip"></div>

        </form>
    </div>
                <!--collapse start-->
            <div class="panel-group m-bot20" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    [查看数据导入结果]
                        </a>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            {% autoescape off %}
                            <h5>{{ rlt }}</h5>
                            {% endautoescape %}
                        </div>
                    </div>
                </div>
            </div>

    <script type="text/javascript">

$("#it").on("change","input[type='file']",function(){
    alert("你哈");
    var filePath=$(this).val();
    if(filePath.indexOf("zip")!==-1 ){
        $(".fileerrorTip").html("").hide();
        var arr=filePath.split('\\');
        var fileName=arr[arr.length-1];
        $(".showFileName").html(fileName);
    }else{
        $(".showFileName").html("");
        $(".fileerrorTip").html("您未上传文件，或者您上传文件类型有误！").show();
        return false
    }
})
</script>
{% endblock %}

mykg/templates/base.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="/static/img/favicon.png">
    <title>软件知识管理平台</title>
    <script src="/static/js/jquery-2.1.1.min.js"></script>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/static/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="/static/fonts/iconfont.css" rel="stylesheet" />
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" />
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/jquery-ui-1.10.4.min.css" rel="stylesheet">
    <link href="/static/css/tagcloud.css" rel="stylesheet">
    <link href="/static/css/tree_style.css" rel="stylesheet">
    <link href="/static/css/footable.bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

</head>

<body>
    <section id="container" class="">
        <header class="header dark-bg" style="padding-top: 0">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="隐藏/显示侧栏" data-placement="bottom">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </div>
            </div>
            <!--logo start-->
            <a href="/" class="logo"> 软件缺陷知识管理平台 <span class="lite">BUG-KG</span></a>
            <!--logo end-->

            <div class="top-nav notification-row">

                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">
                    {% if request.session.username  %}
                        <li>
                            <a  href="{% url 'demo:Logout' %}">
                             <span >欢迎,{{ request.session.username }} </span><i class="iconfont icon-zhuxiaodenglu"></i>
                            <span>注销</span></a>


                    </li>


                    {% elif not request.session.username %}
                        <li>
                           <a class="" href="{% url 'demo:Login' %}">
                            <i class="iconfont icon-denglu-yonghu"></i>
                            <span>用户登录</span>
                        </a>
                        </li>
                    {% endif %}


{#                    <li>#}
{#                        <a href='https://risame.github.io/'>#}
{#                            <i class="fa fa-github" aria-hidden="true"> open Github</i>#}
{#                        </a>#}
{#                    </li>#}
                </ul>
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse " style="background: #1c2434">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">
                    <li class="active">
                        <a class="" href="/overview">
                            <i class="icon_piechart"></i>
                            <span>缺陷知识概览</span>
                        </a>

                    </li>

                    <li>
                        <a class="" href="/search_entity">
                            <i class="icon_genius"></i>
                            <span>实体查询</span>
                        </a>
                    </li>

                     <li>
                        <a class="" href="/relation">
                            <i class=" social_googledrive"></i>
                            <span>关系查询</span>
                        </a>
                    </li>

                    <li>
                        <a class="" href="/shibie">
                            <i class="icon_house_alt"></i>
                            <span>实体识别</span>
                        </a>
                    </li>

                    <li>
                        <a class="" href="/QA">
                            <i class="icon_chat_alt"></i>
                            <span>智能问答</span>
                        </a>
                    </li>

                    <li>
                        <a class="" href="/annotating">
                            <i class="iconfont icon-shujudaoru1"></i>
{#                            <i class="iconfont icon-zhuxiaodenglu"></i>#}
                            <span>数据导入</span>
                        </a>
                    </li>
                    <li>
                        <a class="" href="/test">
                            <i class="iconfont icon-ceshi"></i>
                            <span>测试</span>
                        </a>
                    </li>
                    <li>
                        <a class="" id="biaozhu"  >
                            <i class="fa fa-database"></i>
                            <span>数据标注</span>
                        </a>
                    </li>
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                {% block mainbody %}
                <p>original page</p>
                {% endblock %}

            </section>
        </section>
    </section>

    <!-- javascripts -->
    <script src="/static/js/jquery-ui-1.10.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.scrollTo.min.js"></script>
    <script src="/static/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/static/assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="/static/js/owl.carousel.js"></script>
    <script src="/static/js/jquery.customSelect.min.js"></script>
    <script src="/static/js/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/static/js/jquery-jvectormap-world-mill-en.js"></script>
    <!-- <script src="/static/js/xcharts.min.js"></script> -->
    <!-- <script src="/static/js/jquery.autosize.min.js"></script> -->
    <!-- <script src="/static/js/jquery.placeholder.min.js"></script> -->
    <script src="/static/js/gdp-data.js"></script>
    <!-- <script src="/static/js/morris.min.js"></script> -->
    <!-- <script src="/static/js/sparklines.js"></script> -->
    <!-- <script src="/static/js/charts.js"></script> -->
    <!-- <script src="/static/js/jquery.slimscroll.min.js"></script> -->

    <!-- bootstrap-wysiwyg -->
    <!-- <script src="/static/js/jquery.hotkeys.js"></script>
    <script src="/static/js/bootstrap-wysiwyg.js"></script>
    <script src="/static/js/bootstrap-wysiwyg-custom.js"></script> -->

    <script src="/static/js/gritter.js" type="text/javascript"></script>
     <!-- <script src="/static/js/form-component.js"></script> -->
    <!--custome script for all page-->
{#    <script src="/static/js/scripts.js"></script>#}
    <script src="/static/js/tagcloud.min.js"></script>

    <!--Footable-->
    <script src="/static/js/footable.min.js"> </script>

    <!-- 词云脚本 -->
    <script>
        //knob
        $(function() {
            $(".knob").knob({
                'draw': function() {
                    $(this.i).val(this.cv + '%')
                }
            })
        });

        //carousel
        $(document).ready(function() {
            $("#biaozhu").click(function () {
window.location.href="http://127.0.0.1:8000/";
            });
            $("#owl-slider").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true

            });
        });

        //custom select box

        $(function() {
            $('select.styled').customSelect();
        });
    </script>
    <!--百度统计js end-->



</body>

</html>

mykg/templates/entity.html
{% extends "base.html" %} {% block mainbody %}

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title></title>
        <meta charset="utf-8"/>
        <script src="/static/js/echarts.js"></script>
        {#    <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts-all-3.js"></script>#}
    </head>
    <title>实体</title>
    <div class="container">
        <div class="row">
            <!--head start-->
            <div class="col-md-12">
                <h3 class="page-header"><i class="fa fa-share-alt" aria-hidden="true"></i> 实体查询 </h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a href="\">Home</a></li>
                    <li><i class="fa fa-share-alt" aria-hidden="true"></i>实体查询</li>
                </ol>
            </div>
            <div class="col-md-12">
                <div class="panel panel-default ">
                    <header class="panel-heading">
                        查询条件：
                    </header>
                    <div class="panel-body">
                        <!--搜索框-->
                        <form method="get" id='searchEntityForm'>
                            <div>
                                <div class="input-group">
                                    <input type="text" id="user_text" name="user_text" class="form-control"
                                           placeholder="输入实体名称" aria-describedby="basic-addon1">
                                    <span class="btn btn-primary input-group-addon" type="button"
                                          id="relationSearchButton" style="background-color:#4592fe ; padding:6px 38px"
                                          onclick="document.getElementById('searchEntityForm').submit();">查询</span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>


            </div>
            <p>
            <div class="col-md-12">
                {% if ctx %}
                    <div class="panel panel-default">
                        <header class="panel-heading">
                            <div class="panel-body">
                                <h2>数据库中暂未添加该实体</h2>
                            </div>
                        </header>
                    </div>
                {% endif %}
            </div>
            </p>
            <!--relation start-->
            {% if entityRelation %}
                <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                <div class="col-md-12">
                    <div class="panel " style="background: #1c2434">
                        <header class="panel-heading">
                        </header>
                        <div class="panel-body ">
                            <div id="graph" style="width: 90%;height:600px;"></div>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if entityRelation %}
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <header class="panel-heading">
                            关系列表 :
                        </header>
                        <div class="panel-body">
                            <table class="table" data-paging="true" data-sorting="true"></table>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    {% if entityRelation %}
        <script src="/static/js/jquery.min.js"></script>
        <script type="text/javascript">
            var myChart = echarts.init(document.getElementById('graph'));
            // 将后端的查询结果使用echarts展示
            var ctx = [{{ ctx|safe }}];

            //{entity2,rel}
            var entityRelation = [{{ entityRelation|safe }}];

            var category = [{
                name: '缺陷id',
                color: '#4592FF',
                itemStyle: {
                    normal: {
                        color: "#4592FF",
                        symbolSize: 20
                    }
                },
            }, {
                name: '文本实体',
                color: '#ffa940',
                itemStyle: {
                    normal: {
                        color: "#ffa940",
                        symbolSize: 5
                    }
                }
            }];
            var data = [];
            var links = [];
            if (ctx.length == 0) {
                var node = {};
                var url = decodeURI(location.search);
                var str = "";
                if (url.indexOf("?") != -1) {
                    str = url.split("=")[1]
                }
                //实体１
                node['name'] = str;
                //alert(document.getElementById('user_text').value)
                node['draggable'] = true;
                node['symbolSize'] = 80;
                node['category'] = 0;
                var id = 0;
                node['id'] = id.toString();
                data.push(node);

                //获取实体２，存储在data中，如果实体2已经存在于data中，则不push
                var maxDisPlayNode = 1000;

                for (var i = 0; i < Math.min(maxDisPlayNode, entityRelation[0].length); i++) {
                    node = {};
                    {#alert(entityRelation[0][i]['entity2']['name'])#}
                    node['name'] = entityRelation[0][i]['entity2']['name'];
                    let leng = entityRelation[0][i]['entity2']['name'].length;

                    if (leng > 20) {
                        {#alert(leng);#}
                        node['show'] = false;

                    }
                    node['draggable'] = true;
                    node['symbolSize'] = 20;
                    if ('url' in entityRelation[0][i]['entity2']) {
                        node['category'] = 0;
                    } else {
                        node['category'] = 1;
                    }
                    id = i + 1
                    node['id'] = id.toString();
                    var flag = 1;
                    relationTarget = id.toString();
                    for (var j = 0; j < data.length; j++) {
                        if (data[j]['name'] === node['name']) {
                            flag = 0;
                            relationTarget = data[j]['id'];
                            break;
                        }
                    }
                    relation = {}
                    relation['source'] = 0;
                    relation['target'] = relationTarget;
                    relation['category'] = 0;

                    if (flag === 1) {
                        data.push(node);
                        relation['value'] = entityRelation[0][i]['rel']['type'];
                        relation['symbolSize'] = 10
                        links.push(relation);
                    } else {
                        maxDisPlayNode += 1;
                        for (var j = 0; j < links.length; j++) {
                            if (links[j]['target'] === relationTarget) {
                                links[j]['value'] = links[j]['value'] + " | " + entityRelation[0][i]['rel']['type'];
                                break;
                            }
                        }
                    }
                }


                //用表格列出所有的关系
                tableData = [];
                {#alert(entityRelation[0][1]['rel']['type']);#}
                for (var i = 0; i < entityRelation[0].length; i++) {
                    relationData = {};
                    relationData['entity1'] = str;
                    relationData['relation'] = entityRelation[0][i]['rel']['type'];
                    {#alert(entityRelation[0][i]['rel'][])#}
                    relationData['entity2'] = entityRelation[0][i]['entity2']['name'];
                    {#alert(entityRelation[0][i]['entity2']['name'])#}
                    tableData.push(relationData);
                }
                {#alert(String(tableData));#}
                jQuery(function () {
                    $('.table').footable({
                        "columns": [{"name": "entity1", title: "Entity1"},
                            {"name": "relation", title: "Relation"},
                            {"name": "entity2", title: "Entity2"}],
                        "rows": tableData
                    });
                });

            }
            // 基于准备好的dom，初始化echarts实例

            option = {
                title: {
                    textStyle: { //主标题文本样式{"fontSize": 18,"fontWeight": "bolder","color": "#333"}
                        fontSize: 20,
                        color: "#c8e6c6"
                    },
                    text: '关系图',
                },
                tooltip: {
                    formatter: function (x) {
                        return x.data.des;
                    }
                },
                toolbox: {
                    // 显示工具箱
                    show: true,
                    feature: {
                        mark: {
                            show: true
                        },
                        // 还原
                        restore: {
                            show: true
                        },
                        // 保存为图片
                        saveAsImage: {
                            show: true
                        }
                    },
                },
                label: {
                    normal: {
                        show: true,
                        position: "inside",
                        textStyle: {
                            fontSize: 20,
                            color: "#c8e6c6"
                        },
                    }
                },
                legend: {//图例的样式设置
                    backgroundColor: '#c9d8cd',
                    data: category.map(function (a) {
                        return a.name;
                    }),
                },
                series: [
                    {
                        type: 'graph',
                        layout: 'force',
                        symbolSize: 50,
                        focusNodeAdjacency: true,
                        roam: true,
                        edgeSymbol: ['circle', 'arrow'],
                        edgeSymbolSize: [2, 10],
                        edgeLabel: {//关系边的属性设置
                            normal: {
                                show: true,
                                textStyle: {
                                    fontSize: 12,

                                },
                                formatter: "{c}"
                            }
                        },
                        lineStyle: {
                            normal: {
                                {#opacity: 0.9,#}
                                width: 2,
                                color: "#c8e6c6",
                                {#curveness: 0,#}
                            }
                        },
                        label: {//结点上的文字属性设置
                            normal: {
                                show: true,
                                textStyle: {
                                    fontSize: 20,
                                    fontStyle: 'oblique',
                                    fontWeight: 'bolder',
                                    color: "#ffffff",

                                },
                            }
                        },
                        force: {
                            repulsion: 1900,
                            edgeLength: [55, 35]
                        },
                        animationEasingUpdate: "quinticInOut",          // 数据更新动画的缓动效果。[ default: cubicOut ]    "quinticInOut"
                        animationDurationUpdate: 1000,
                        categories: category,
                        data: data,
                        links: links,
                    }
                ]
            };
            // 数据更新动画的时长。[ default: 300 ]
            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
        </script>
    {% endif %}

{% endblock %}

mykg/templates/index.html
{% extends "base.html" %}

{% block mainbody %}

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <!--overview start-->
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-header"><i class="fa fa-search"></i> 实体识别 </h3>
                    <ol class="breadcrumb">
                        <li><i class="fa fa-home"></i><a href="\">Home</a></li>
                        <li><i class="fa fa-search"></i>实体识别</li>
                    </ol>
                </div>
            </div>

            <section class="panel panel-default">
                <header class="panel-heading">
                    输入文本 :
                </header>
                <div class="panel-body">
                    <form action="/ER-post/" method="post">
                        <div class="form-group">
                            {% csrf_token %}
                            <textarea type="text" name="user_text" class="form-control" placeholder="Enter text" style="height:140px"> </textarea>
                        </div>
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                            <button type="submit" class="btn-primary btn-lg btn-block"> 提交！ </button>
                        </div>
                        <div class="col-md-4"></div>
                    </form>
                </div>
            </section>
            <!--collapse start-->
            <div class="panel-group m-bot20" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    [查看识别结果]
                        </a>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            {% autoescape off %}
                            <h5>{{ rlt }}</h5>
                            {% endautoescape %}
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                    [查看分词结果]
                            </a>

                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            {% autoescape off %}
                            <h5> {{ seg_word }}</h5>
                            {% endautoescape %}
                        </div>
                    </div>
                </div>

            </div>
            <!--collapse end-->

        </div>

    </div>
</div>

{% endblock %}